# This file is generated by `tools/abi.R`, do not modify by hand

tree_sitter_abi <- function() {
  TREE_SITTER_LANGUAGE_VERSIONL
}

tree_sitter_minimum_compatible_abi <- function() {
  TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSIONL
}
